
<style>
    .custom-table {
        width: 100%;
        table-layout: fixed;
    }
    .col3-layout .col-wrapper {
    float: left;
    width: 103.16667%;
    }

    .col3-layout .col-wrapper .col-main {
    float: left;
    width: 101.68421%;
    }
</style>

<table class="data-table custom-table">
    <colgroup>
        <col width="15%">
        <col width="60%">
        <col width="10%">
        <col width="10%">
    </colgroup>
    <thead>
        <tr class="headings">
            <th><?php echo $this->__('No.'); ?></th>
            <th><?php echo $this->__('Description'); ?></th>
            <th><?php echo $this->__('Grid'); ?></th>
            <th><?php echo $this->__('View'); ?></th>
        </tr>
    </thead>
    <tbody>
            <tr>
                <td>1.</td>
                <td>Need a list of product with these columns product name, sku, cost, price, color.</td>
                <td><a href="<?php echo $this->getUrl('*/*/one'); ?>"><?php echo $this->__('Grid'); ?></a></td>
                <td><a href="<?php echo $this->getUrl('*/*/viewone'); ?>"><?php echo $this->__('View'); ?></a></td>
            </tr>

            <tr>
                <td>2.</td>
                <td>Need a list of attribute & options. return an array with attribute id, attribute code, option Id, option name.</td>
                <td><a href="<?php echo $this->getUrl('*/*/two'); ?>"><?php echo $this->__('Grid'); ?></a></td>
                <td><a href="<?php echo $this->getUrl('*/*/viewtwo'); ?>"><?php echo $this->__('View'); ?></a></td>
            </tr>

            <tr>
                <td>3.</td>
                <td>Need a list of attribute having options count greater than 10. return array with attribute id, attribute code, option count.</td>
                <td><a href="<?php echo $this->getUrl('*/*/three'); ?>"><?php echo $this->__('Grid'); ?></a></td>
                <td><a href="<?php echo $this->getUrl('*/*/viewthree'); ?>"><?php echo $this->__('View'); ?></a></td>
            </tr>

            <tr>
                <td>4.</td>
                <td>Need list of product with assigned images. return an array with product Id, sku, base image, thumb image, small image.</td>
                <td><a href="<?php echo $this->getUrl('*/*/four'); ?>"><?php echo $this->__('Grid'); ?></a></td>
                <td><a href="<?php echo $this->getUrl('*/*/viewfour'); ?>"><?php echo $this->__('View'); ?></a></td>
            </tr>
            <tr>
                <td>5.</td>
                <td>Need list of product with gallery image count. return an array with product sku, gallery images count, without consideration of thumb, small, base</td>
                <td><a href="<?php echo $this->getUrl('*/*/five'); ?>"><?php echo $this->__('Grid'); ?></a></td>
                <td><a href="<?php echo $this->getUrl('*/*/viewfive'); ?>"><?php echo $this->__('View'); ?></a></td>
            </tr>
            <tr>
                <td>6.</td>
                <td>Need list of top to bottom customers with their total order counts. return an array with customer id, customer name, customer email, order count.</td>
                <td><a href="<?php echo $this->getUrl('*/*/six'); ?>"><?php echo $this->__('Grid'); ?></a></td>
                <td><a href="<?php echo $this->getUrl('*/*/viewsix'); ?>"><?php echo $this->__('View'); ?></a></td>
            </tr>
            <tr>
                <td>7.</td>
                <td>Need list of top to bottom customers with their total order counts, order status wise. return an array with customer id, customer name, customer email, status, order count.</td>
                <td><a href="<?php echo $this->getUrl('*/*/seven'); ?>"><?php echo $this->__('Grid'); ?></a></td>
                <td><a href="<?php echo $this->getUrl('*/*/viewseven'); ?>"><?php echo $this->__('View'); ?></a></td>
            </tr>
            <tr>
                <td>8.</td>
                <td>Need list product with number of quantity sold till now for each. return an array with product id, sku, sold quantity.</td>
                <td><a href="<?php echo $this->getUrl('*/*/eight'); ?>"><?php echo $this->__('Grid'); ?></a></td>
                <td><a href="<?php echo $this->getUrl('*/*/vieweight'); ?>"><?php echo $this->__('View'); ?></a></td>
            </tr>
            <tr>
                <td>9.</td>
                <td>Need list of those attributes for whose value is not assigned to product. return an array result product wise with these columns product Id, sku, attribute Id, attribute code</td>
                <td><a href="<?php echo $this->getUrl('*/*/nine'); ?>"><?php echo $this->__('Grid'); ?></a></td>
                <td><a href="<?php echo $this->getUrl('*/*/viewnine'); ?>"><?php echo $this->__('View'); ?></a></td>
            </tr>
            <tr>
                <td>10.</td>
                <td>Need list of those attributes for whose value is not assigned to product. return an array result product wise with these columns product Id, sku, attribute Id, attribute code, value.</td>
                <td><a href="<?php echo $this->getUrl('*/*/ten'); ?>"><?php echo $this->__('Grid'); ?></a></td>
                <td><a href="<?php echo $this->getUrl('*/*/viewten'); ?>"><?php echo $this->__('View'); ?></a></td>
            </tr>


    </tbody>
</table>







