<?php 
$brands = Mage::getModel('brand/brand')->getCollection()->addOrder('sort_order','DESC');

 ?>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

 


  <!-- Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

  <div class="title"><span class="brand-title1">Featured </span><span class="brand-title2"> Brands</span></div>

<div class="Brands">
  <?php foreach ($brands as $key => $value): ?>
  	
  <div class="card m-1 brand" style="width: 18rem; ">
    <a href="<?php echo $this->getUrl('brand/'.$value->url_key); ?>">
  <img class="card-img-top card-image" src="<?php echo Mage::getBaseUrl('media').$value->image ?>" alt="Card image cap">
</a>
  <div class="card-body">
    <h5 class="card-title card-text"><?php echo $value->name ?></h5>
  </div>
</div>
  <?php endforeach ?>
</div>

<style type="text/css">
.brand{
 float: left;
  width: 25%;
  padding: 0 10px;
}
.brands:after
{
  content: "";
  display: table;
  clear: both;
  display: table;
  clear: both;
}
.card-image{
height: 284px;
}
.card-text
{
  text-align: center;
}
.title
{
  text-align: center;
}
.brand-title1
{
  color: black;
  font-weight: 500;
  font-size: 25px;
}

.brand-title2
{
  font-weight: 500;
  color: #0e259a;
  font-size: 25px;
}

</style>


