<?php 
$brands = Mage::getModel('brand/brand')->getCollection()->addOrder('sort_order','DESC');

 ?>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

 


  <!-- Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<div style="display:flex;">
  <?php foreach ($brands as $key => $value): ?>
  	
  <div class="card m-1" style="width: 18rem; ">
  <img class="card-img-top card-image" src="<?php echo Mage::getBaseUrl('media').$value->image ?>" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title"><?php echo $value->name ?></h5>
    <p class=""><?php echo $value->description ?></p>
    <a href="<?php echo $this->getUrl('brand/'.$value->url_key); ?>" class="btn btn-primary">Explore</a>
  </div>
</div>
  <?php endforeach ?>
</div>

<style type="text/css">

.card-image{
height: 284px;
}
</style>

<script type="text/javascript">
function brandclick()
{
	window.location.assign('<?php echo $this->getUrl('brand/'.$value->url_key); ?>')
}
</script>


