<?php $brandId =  $this->getRequest()->getParam('brand_id');
$products = $this->getProductsByBrand();
$brand = Mage::getModel('brand/brand')->load($brandId);
?>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

<div class="container">
  <div class="img-fluid"><img class="banner-img" src="<?php echo Mage::getBaseUrl('media').$brand->banner_image ?>" alt="Snow" ></div>
  <div class="banner-text">
    <div class="brand-title1"><?php echo $brand->name; ?></div>
    <div class="brand-title2"><?php echo $brand->description; ?></div>
  </div>
</div>
<div style="display:flex;">
  <?php foreach ($products as $key => $value): ?>
  
  
  <!-- <div class="card m-1" style="width: 18rem; ">
    <img class="card-img-top card-image" src="<?php echo Mage::getBaseUrl('media').'catalog/product' . $value->getImage() ?>" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title"><?php echo $value->name ?></h5>
      <p class=""><?php echo $value->getShortDescription() ?></p>
      <p class=""><b>$ <?php echo $value->getPrice() ?></b></p>
      <a href="<?php echo $this->getUrl($this->getProductUrl($value)); ?>" class="btn btn-primary">View</a>
    </div>
  </div> -->
  <?php endforeach ?>

</div>


<div class="Brands">
  <?php foreach ($products as $key => $value): ?>
    
  <div class="card m-1 brand" style="width: 13rem; ">
    <a href="<?php echo $this->getUrl($this->getProductUrl($value)); ?>">
  <img class="card-img-top card-image" src="<?php echo Mage::getBaseUrl('media').'catalog/product' . $value->getImage() ?>" alt="Card image cap">
</a>
  <div class="card-body">
    <h5 class="card-title card-text"><?php echo $value->name ?></h5>
      <p class=""><?php echo $value->getShortDescription() ?></p>
      <p class=""><b>$ <?php echo $value->getPrice() ?></b></p>
  </div>
</div>
  <?php endforeach ?>
</div>


<style type="text/css">
.container {
position: relative;
text-align: center;
color: white;
}
.text-container {
position: relative;
z-index: 1;
text-align: center;
color: #fff;
padding: 20px;
}
.main-text {
font-size: 36px;
font-weight: bold;
margin-bottom: 10px;
}
.sub-text {
font-size: 18px;
}
.banner-img{
height: 419px;
width: 1300px;
margin-left: -328px;
}
.banner-text{
      text-align: left;
    margin-top: -255px;
    margin-bottom: 206px
}

.brand-title2{

}
.brand-title1
{
  color: black;
  font-weight: 500;
  font-size: 25px;
}

.brand-title2
{
  font-weight: 500;
  color: black;
  font-size: 25px;
}
.brand{
 float: left;
  width: 20%;
  padding: 0 10px;
}

.brands:after
{
  content: "";
  display: table;
  clear: both;
  display: table;
  clear: both;
}
</style>